### ISSUE TITLE
Pendência na pagina finalizar compra

### ISSUE THREAD

**Issue by LudmilaBGomes** [jessicacardoso1/compra-certa#1]
![image](https://user-images.githubusercontent.com/60022146/115098571-1c1a3880-9f07-11eb-8819-b4ce37836d41.png)

Pendência no "parcelas"

**Comment by fsilva-c** [comment]
Ok!

![Captura de tela de 2021-04-17 17-31-50](https://user-images.githubusercontent.com/50850709/115126071-ddd25700-9fa2-11eb-9f62-f1b568c888b0.png)

 Fiz as seguintes alterações no form: incluí uma nova row e duas coluna para armazenar a label e o select das parcelas.

![Captura de tela de 2021-04-17 17-33-47](https://user-images.githubusercontent.com/50850709/115126095-1b36e480-9fa3-11eb-96c8-a842aa559655.png)
